AuthorizationCenter/Controllers/SignController.cs
using AuthorizationCenter.Define;
using AuthorizationCenter.Dto.Jsons;
using AuthorizationCenter.Dto.Requests;
using AuthorizationCenter.Managers;
using AuthorizationCenter.Entitys;
using AuthorizationCenter.Stores;
using AuthorizationCenter.ViewModels.Sign;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WS.Core;
using WS.Log;
using WS.Text;

namespace AuthorizationCenter.Controllers
{
    /// <summary>
    /// 登陆控制器
    /// </summary>
    public class SignController : Controller
    {
        /// <summary>
        /// 日志器
        /// </summary>
        public ILogger Logger = LoggerManager.GetLogger<SignController>();

        /// <summary>
        /// 用户管理
        /// </summary>
        public IUserManager<UserJson> UserManager { get; set; }

        /// <summary>
        /// Session
        /// </summary>
        public ISession Session => HttpContext.Session;
        
        /// <summary>
        /// 构造器
        /// </summary>
        /// <param name="userManager"></param>
        public SignController(IUserManager<UserJson> userManager)
        {
            UserManager = userManager;
        }

        /// <summary>
        /// 登陆主页
        /// </summary>
        /// <returns></returns>
        [Filters.NoSign]
        public ViewResult Index(string returnUrl = null)
        {
            ViewData["returnUrl"] = returnUrl??"/User/Index";
            return View();
        }

        /// <summary>
        /// 注册
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [Filters.NoSign]
        public async Task<IActionResult> SignUp([FromForm]ModelRequest<UserJson> request)
        {
            // 响应体构建
            ResponseMessage<UserJson> response = new ResponseMessage<UserJson>();

            Console.WriteLine(JsonUtil.ToJson(request));

            try
            {
                // 用户创建
                await UserManager.Create(request.Data);
                //await UserManager.Create(response, request);
            }
            catch (Exception e)
            {
                Logger.Error($"[{nameof(SignUp)}] 用户创建失败：\r\n{e.ToString()}");
            }
            return RedirectToAction(nameof(UserController.Index), nameof(UserController));
            //return RedirectToRoute(new { controller = nameof(UserController), action = nameof(UserController.Index) });
        }

        /// <summary>
        /// 签入
        /// </summary>
        /// <param name="request">请求</param>
        /// <param name="returnUrl">返回URL（跳转）</param>
        /// <returns></returns>
        [Filters.NoSign]
        [HttpPost]
        public async Task<IActionResult> SignIn([Required]SignInViewModel request, string returnUrl = null)
        {
            Logger.Trace("returnUrl: " + returnUrl+ "\r\nrequest: " +JsonUtil.ToJson(request));

            ViewData["returnUrl"] = returnUrl;

            // 参数检查
            if (string.IsNullOrWhiteSpace(request.SignName) || string.IsNullOrWhiteSpace(request.PassWord))
            {
                Logger.Trace($"[{nameof(SignIn)}] 用户名或密码不能为空");
                ModelState.AddModelError("All", "用户名或密码不能为空");
                return View(request);
            }
            // 登陆成功
            if (await UserManager.Exist(user=>user.SignName== request.SignName&&user.PassWord==request.PassWord))
            {
                SignUser = await UserManager.FindByName(request.SignName).SingleOrDefaultAsync();
                Logger.Trace("登陆成功");
                if (returnUrl != null)
                {
                    return RedirectToLocal(returnUrl);
                }
                else
                {
                    return RedirectToAction(nameof(HomeController.Index), nameof(HomeController));
                }
            }
            // 登陆失败
            else
            {
                Logger.Trace("登陆失败");
                ModelState.AddModelError("All", "用户名或密码错误");
                return View(nameof(Index), request);
            }
        }

        /// <summary>
        /// 获取登陆用户简要信息 -每次都是新建一个UserBaseJson对象
        /// </summary>
        /// <returns></returns>
        /// <summary>
        /// 登陆用户
        /// </summary>
        private UserJson SignUser
        {
            get
            {
                if (HttpContext.Session.GetString(Constants.USERID) == null)
                {
                    return null;
                }
                return new UserJson
                {
                    Id = HttpContext.Session.GetString(Constants.USERID),
                    SignName = HttpContext.Session.GetString(Constants.SIGNNAME),
                    PassWord = HttpContext.Session.GetString(Constants.PASSWORD)
                };
            }
            set
            {
                if (value == null)
                {
                    HttpContext.Session.Remove(Constants.USERID);
                    HttpContext.Session.Remove(Constants.SIGNNAME);
                    HttpContext.Session.Remove(Constants.PASSWORD);
                }
                else
                {
                    HttpContext.Session.SetString(Constants.USERID, value.Id);
                    HttpContext.Session.SetString(Constants.SIGNNAME, value.SignName);
                    HttpContext.Session.SetString(Constants.PASSWORD, value.PassWord);
                }
            }
        }

        /// <summary>
        /// 签出 Clear Session SignUser
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [Filters.NoSign]
        public IActionResult SignOut(ModelRequest<UserJson> request)
        {
            SignUser = null;
            return View(nameof(Index));
        }

        private IActionResult RedirectToLocal(string returnUrl)
        {
            Console.WriteLine("登陆跳转URL："+returnUrl);
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), HomeController.Name);
            }
        }

        /// <summary>
        /// 将ActionURL解析出ActionName与ControllerName
        /// 再重定向到Action并传递参数
        /// </summary>
        /// <param name="actionURL"></param>
        /// <param name="routeValues"></param>
        /// <returns></returns>
        private IActionResult RedirectUrlToAction(string actionURL, object routeValues)
        {
            Console.WriteLine("RedirectUrlToAction--跳转URL：" + actionURL);
            if (Url.IsLocalUrl(actionURL))
            {
                int lastIndex = actionURL.LastIndexOf('/');
                var ActionName = actionURL.Substring(lastIndex, actionURL.Length-lastIndex);
                Console.WriteLine("ActionName: " + ActionName);
                int secondIndex = actionURL.Substring(0, lastIndex).LastIndexOf('/');
                var ControllerName = actionURL.Substring(secondIndex, lastIndex-secondIndex);
                Console.WriteLine("ControllerName: " + ControllerName);
                return RedirectToAction(ActionName, ControllerName, routeValues);
            }
            else
            {
                // 不是本地地址的话就去主页
                return RedirectToAction(nameof(HomeController.Index), HomeController.Name);
            }
        }
    }
}

AuthorizationCenter/Controllers/UserController.cs
using AuthorizationCenter.Define;
using AuthorizationCenter.Dto.Jsons;
using AuthorizationCenter.Entitys;
using AuthorizationCenter.Managers;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using WS.Log;
using WS.Text;

namespace AuthorizationCenter.Controllers
{
    /// <summary>
    /// 用户控制
    /// </summary>
    public class UserController : Controller
    {
        /// <summary>
        /// 用户管理
        /// </summary>
        IUserManager<UserJson> UserManager { get; set; }

        /// <summary>
        /// 角色管理
        /// </summary>
        IRoleManager<RoleJson> RoleManager { get; set; }

        /// <summary>
        /// 组织管理
        /// </summary>
        IOrganizationManager OrganizationManager { get; set; }

        /// <summary>
        /// 用户角色关联管理
        /// </summary>
        IUserRoleManager UserRoleManager { get; set; }

        /// <summary>
        /// 角色组织权限管理
        /// </summary>
        IRoleOrgPerManager RoleOrgPerManager { get; set; }
        
        /// <summary>
        /// 类型映射
        /// </summary>
        IMapper Mapper { get; set; }

        /// <summary>
        /// 日志器
        /// </summary>
        readonly ILogger Logger = LoggerManager.GetLogger<UserController>();

        /// <summary>
        /// 
        /// </summary>
        /// <param name="userManager"></param>
        /// <param name="roleManager"></param>
        /// <param name="organizationManager"></param>
        /// <param name="userRoleManager"></param>
        /// <param name="roleOrgPerManager"></param>
        /// <param name="mapper"></param>
        public UserController(IUserManager<UserJson> userManager, IRoleManager<RoleJson> roleManager, IOrganizationManager organizationManager, IUserRoleManager userRoleManager, IRoleOrgPerManager roleOrgPerManager, IMapper mapper)
        {
            UserManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            RoleManager = roleManager ?? throw new ArgumentNullException(nameof(roleManager));
            OrganizationManager = organizationManager ?? throw new ArgumentNullException(nameof(organizationManager));
            UserRoleManager = userRoleManager ?? throw new ArgumentNullException(nameof(userRoleManager));
            RoleOrgPerManager = roleOrgPerManager ?? throw new ArgumentNullException(nameof(roleOrgPerManager));
            Mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }
        
        /// <summary>
        /// 列表 -跳转到列表界面
        /// </summary>
        /// <returns></returns>
        // GET: UserBaseJsons
        public async Task<IActionResult> Index(string orgId, int pageIndex =0, int pageSize =10)
        {
            Logger.Trace($"[{nameof(Index)}] 用户[{SignUser.SignName}]({SignUser.Id})查询组织({orgId??"可见"})下的用户列表, 请求参数: pageIndex: {pageIndex}, pageSize: {pageSize}");
            ViewData[Constants.SIGNUSER] = SignUser;
            try
            {
                if (orgId == null)
                {
                    // 1. 权限验证 -该用户是否存在该权限
                    if (!await RoleOrgPerManager.HasPermission(SignUser.Id, Constants.USER_QUERY))
                    {
                        Logger.Warn($"[{nameof(Index)}] 用户[{SignUser.SignName}]({SignUser.Id})没有权限({Constants.USER_QUERY})");
                        ModelState.AddModelError("All", "没有权限");
                        return RedirectToAction(nameof(HomeController.Index), HomeController.Name);
                    }
                    // 2. 业务处理
                    var users = await UserManager.FindByUserId(SignUser.Id);
                    // 分页查询用户列表 
                    var pageBody = users.Page(pageIndex, pageSize);
                    var data = pageBody.Data;
                    Logger.Trace($"[{nameof(Index)}] 响应数据:\r\n{JsonUtil.ToJson(data)}");
                    ViewData["PageBody"] = pageBody;
                    return View(data);
                }
                else
                {
                    // 1. 权限验证 -该用户在组织(orgId)下是否存在该权限
                    if (!await RoleOrgPerManager.HasPermission(SignUser.Id, Constants.USER_QUERY, orgId))
                    {
                        Logger.Warn($"[{nameof(Index)}] 用户[{SignUser.SignName}]({SignUser.Id})在组织({orgId})下没有权限({Constants.USER_QUERY})");
                        ModelState.AddModelError("All", "没有权限");
                        return RedirectToAction(nameof(HomeController.Index), HomeController.Name);
                    }
                    // 2. 业务处理
                    var users = await UserManager.FindByUserIdOrgId(SignUser.Id, orgId);
                    // 分页查询用户列表 
                    var pageBody = users.Page(pageIndex, pageSize);
                    var data = pageBody.Data;
                    Logger.Trace($"[{nameof(Index)}] 响应数据:\r\n{JsonUtil.ToJson(data)}");
                    ViewData["PageBody"] = pageBody;
                    return View(data);
                }
            }
            catch(Exception e)
            {
                Logger.Error($"[{nameof(Index)}] 服务器错误:\r\n{e.ToString()}");
                return RedirectToAction(nameof(HomeController.Index), HomeController.Name);
            }
        }

        /// <summary>
        /// 详情 -跳转到详情界面
        /// </summary>
        /// <param name="id">用户ID</param>
        /// <returns></returns>
        // GET: UserBaseJsons/Details/5
        public async Task<IActionResult> Details(string id)
        {
            Logger.Trace($"[{nameof(Details)}] 查看用户详情 用户ID: {id}");
            // 0. 检查参数
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                // 1. 权限检查
                if (!(await RoleOrgPerManager.HasPermissionForUser(SignUser.Id, Constants.USER_QUERY, id)))
                {
                    Logger.Warn($"用户[{SignUser.SignName}]({SignUser.Id})没有权限({Constants.USER_QUERY})操作用户({id})");
                    ModelState.AddModelError("All", "没有权限");
                    return RedirectToAction(nameof(Index));
                }
                // 2. 业务处理
                var user = await UserManager.FindById(id).SingleOrDefaultAsync();
                Logger.Trace($"[{nameof(Details)}] 响应数据:\r\n{JsonUtil.ToJson(user)}");
                if (user == null)
                {
                    return NotFound();
                }
                else
                {
                    // 再查询用户绑定的角色列表
                    ViewData[Constants.ROLES] = await RoleManager.FindByUserId(id);
                    ViewData[Constants.USERROLES] = await UserRoleManager.FindByUserId(id).ToListAsync();
                    ViewData["Organization"] = (await OrganizationManager.FindFromUOByUserId(SignUser.Id)).SingleOrDefault();
                    return View(user);
                }
            }
            catch (Exception e)
            {
                Logger.Error($"[{nameof(Details)}] 服务器错误:\r\n{e}");
                return RedirectToAction(nameof(Index));
            }
            
        }

        /// <summary>
        /// [MVC] 跳转到用户新建界面
        /// 在组织(orgId)下创建用户
        /// </summary>
        /// <param name="orgId">组织ID</param>
        /// <returns></returns>
        // GET: UserBaseJsons/Create
        public async Task<IActionResult> Create(string orgId)
        {
            Logger.Trace($"[{nameof(Create)}] 用户[{SignUser.SignName}]({SignUser.Id})跳转到用户新建界面, 请求参数:{nameof(orgId)}({orgId})");
            try
            {
                // 1. 权限验证
                if (orgId == null)
                {
                    if (!await RoleOrgPerManager.HasPermissionInSelfOrg(SignUser.Id, Constants.USER_CREATE))
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                else
                {
                    if (!await RoleOrgPerManager.HasPermission(SignUser.Id, Constants.USER_CREATE, orgId))
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                // 查询有权限添加用户的组织
                var organizations = await RoleOrgPerManager.FindOrgByUserIdPerName(SignUser.Id, Constants.USER_CREATE);
                ViewData["OrgId"] = new SelectList(organizations, nameof(Organization.Id), nameof(Organization.Name), orgId);
                return View();
            }
            catch(Exception e)
            {
                Logger.Error($"[{nameof(Details)}] 用户[{SignUser.SignName}]({SignUser.Id})跳转界面(在组织({orgId})下创建用户)失败, 服务器错误:\r\n{e}");
                ViewData["ErrMsg"] = e.Message;
                return RedirectToAction(nameof(Index));
            }
        }

        /// <summary>
        /// MVC 创建 -在数据库中添加数据
        /// </summary>
        /// <param name="orgId">组织ID</param>
        /// <param name="userJson">被创建用户</param>
        /// <returns></returns>
        // POST: UserBaseJsons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string orgId, UserJson userJson)
        {
            Logger.Trace($"[{nameof(Create)}] 用户[{SignUser.SignName}]({SignUser.Id})在组织({orgId??"本组织"})新增用户:\r\n{JsonUtil.ToJson(userJson)}");
            // 0. 检查参数
            if (string.IsNullOrWhiteSpace(userJson.SignName) || string.IsNullOrWhiteSpace(userJson.PassWord))
            {
                ModelState.AddModelError("All", "用户名或密码不能为空");
                // 查询有权限添加用户的组织 -TODO: 测试这个东西有没问题
                return RedirectToAction(nameof(Create), new { orgId });
            }
            try
            {

AuthorizationCenter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AuthorizationCenter</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">授权中心</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="User" asp-action="Index">用户管理</a></li>
                    <li><a asp-area="" asp-controller="UserRoles" asp-action="Index">角色绑定</a></li>
                    <li><a asp-area="" asp-controller="Roles" asp-action="Index">角色管理</a></li>
                    <li><a asp-area="" asp-controller="Organization" asp-action="Index">组织管理</a></li>
                    <li><a asp-area="" asp-controller="Permission" asp-action="Index">权限管理</a></li>
                    <li><a asp-area="" asp-controller="RoleOrgPer" asp-action="Index">授权管理</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Sign" asp-action="Index">登陆|注册</a></li>
                    <li><a asp-area="" asp-controller="Sign" asp-action="SignOut">登出</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - 授权中心</p>
        </footer>
    </div>
    @* 开发环境 *@
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="/lib/jquery.ztree.core.js"></script>
        <script src="/lib/jquery.ztree.excheck.js"></script>
        <script src="/lib/jquery.ztree.exedit.js"></script>
        <script src="/js/site.js" asp-append-version="true"></script>
    </environment>
    @* 非开发环境 *@
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="/lib/jquery.ztree.core.js"></script>
        <script src="/lib/jquery.ztree.excheck.js"></script>
        <script src="/lib/jquery.ztree.exedit.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @* 将其它布局文件中的Scripts导入 *@
    @RenderSection("Scripts", required: false)
</body>
</html>